// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/3/2026, 2:09:15 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/plugins/**/*.{js,ts,mjs}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/composables/**/*.{js,ts,mjs}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/utils/**/*.{js,ts,mjs}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/SBS/Desktop/workspace/medaminefh.github.io/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;