name: Build nuxt4-migration and Deploy to Main

on:
  push:
    branches:
      - nuxt4-migration

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Generate Static Site
        run: npx nuxt generate # This forces Nuxt to build static HTML files instead of a Node server

      - name: Add .nojekyll to prevent 404s on _nuxt assets
        run: touch .output/public/.nojekyll

      - name: Deploy Public Folder to Main Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .output/public # Nuxt puts the static index.html here!
          branch: main
          clean: true
          single-commit: false
