name: Build nuxt4-migration and Deploy to Main

on:
  push:
    branches:
      - nuxt4-migration

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Fixed the setup-node action here
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install # Changed from npm ci to handle missing lockfiles

      - name: Build Project
        run: npm run build

      - name: Deploy Build Folder to Main Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .output
          branch: main
          clean: true
          single-commit: false
